version: '3.8'

services:
  backend:
    build: .
    ports:
      - '5000:5000'
    environment:
      - MONGO_URI=${MONGO_URI}
      - PORT=${PORT}
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0.2
    ports:
      - '27017:27017'

  swagger:
      image: swaggerapi/swagger-ui
      ports:
        - '8080:8080'
      environment:
        - SWAGGER_JSON=/api-docs/swagger.yaml
      volumes:
        - ./swagger.yaml:/api-docs/swagger.yaml
      depends_on:
        - backend
