version: '3.8'

services:
  backend:
    build: .
    ports:
      - '5000:5000'
    environment:
      - MONGO_URI=${MONGO_URI}
      - PORT=${PORT}

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
