version: '3.8'

services:
  backend:
    build: .
    ports:
      - '5000:5000'
    environment:
      - MONGO_URI=${MONGO_URI}
      - PORT=${PORT}
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0.2
    ports:
      - '27017:27017'
